### ISSUE TITLE
MoreInterviewQuestions

### ISSUE THREAD

**Issue by AmandaJanice** [jaortiz117/MoonBuggyInterview#1]
Databases if apply (Technical):
How can we create a database? 
Answer: First we create a server, locally or external, with an username and password (password is optional). Then we create the database on the server. Finally on the newly created DB we create as many tables as needed. Note* Is important to develop a simple sketch to know how the tables are going to work and determine how many tables are needed.

Following up: How can we link two different tables?
Answer: with a primary and/or foreign key.

Verifying interest on the team:
What do you know about the Moonbuggy? (At least que mencione la competencia)
Following up: What is the purpose of the Telemetry department?
Note: Estas preguntas se pueden contestar si busco en internet y leyó la pagina del equipo.

**Comment by jaortiz117** [comment]
great questions! will be applying them tonight

**Comment by jaortiz117** [comment]
already added the questions! thanks for the input
